spring.application.name=api-gateway
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=users-api
spring.cloud.gateway.routes[0].uri=lb://users-api
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users, /api/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=movies-api
spring.cloud.gateway.routes[1].uri=lb://movies-api
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/movies, /api/movies/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

logging.level.org.springframework.cloud.gateway=DEBUG